# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Activity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'week': 'object',
        'statuses': 'object',
        'logins': 'object',
        'registrations': 'object'
    }

    attribute_map = {
        'week': 'week',
        'statuses': 'statuses',
        'logins': 'logins',
        'registrations': 'registrations'
    }

    def __init__(self, week=None, statuses=None, logins=None, registrations=None):  # noqa: E501
        """Activity - a model defined in Swagger"""  # noqa: E501
        self._week = None
        self._statuses = None
        self._logins = None
        self._registrations = None
        self.discriminator = None
        self.week = week
        self.statuses = statuses
        self.logins = logins
        self.registrations = registrations

    @property
    def week(self):
        """Gets the week of this Activity.  # noqa: E501

        Midnight at the first day of the week. UNIX timestamp.  # noqa: E501

        :return: The week of this Activity.  # noqa: E501
        :rtype: object
        """
        return self._week

    @week.setter
    def week(self, week):
        """Sets the week of this Activity.

        Midnight at the first day of the week. UNIX timestamp.  # noqa: E501

        :param week: The week of this Activity.  # noqa: E501
        :type: object
        """
        if week is None:
            raise ValueError("Invalid value for `week`, must not be `None`")  # noqa: E501

        self._week = week

    @property
    def statuses(self):
        """Gets the statuses of this Activity.  # noqa: E501

        Statuses created since the week began. String cast from an integer.  # noqa: E501

        :return: The statuses of this Activity.  # noqa: E501
        :rtype: object
        """
        return self._statuses

    @statuses.setter
    def statuses(self, statuses):
        """Sets the statuses of this Activity.

        Statuses created since the week began. String cast from an integer.  # noqa: E501

        :param statuses: The statuses of this Activity.  # noqa: E501
        :type: object
        """
        if statuses is None:
            raise ValueError("Invalid value for `statuses`, must not be `None`")  # noqa: E501

        self._statuses = statuses

    @property
    def logins(self):
        """Gets the logins of this Activity.  # noqa: E501

        User logins since the week began. String cast from an integer.  # noqa: E501

        :return: The logins of this Activity.  # noqa: E501
        :rtype: object
        """
        return self._logins

    @logins.setter
    def logins(self, logins):
        """Sets the logins of this Activity.

        User logins since the week began. String cast from an integer.  # noqa: E501

        :param logins: The logins of this Activity.  # noqa: E501
        :type: object
        """
        if logins is None:
            raise ValueError("Invalid value for `logins`, must not be `None`")  # noqa: E501

        self._logins = logins

    @property
    def registrations(self):
        """Gets the registrations of this Activity.  # noqa: E501

        User registrations since the week began. String cast from an integer.  # noqa: E501

        :return: The registrations of this Activity.  # noqa: E501
        :rtype: object
        """
        return self._registrations

    @registrations.setter
    def registrations(self, registrations):
        """Sets the registrations of this Activity.

        User registrations since the week began. String cast from an integer.  # noqa: E501

        :param registrations: The registrations of this Activity.  # noqa: E501
        :type: object
        """
        if registrations is None:
            raise ValueError("Invalid value for `registrations`, must not be `None`")  # noqa: E501

        self._registrations = registrations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Activity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Activity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
