# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnnouncementReaction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'count': 'object',
        'me': 'object',
        'url': 'object',
        'static_url': 'object'
    }

    attribute_map = {
        'name': 'name',
        'count': 'count',
        'me': 'me',
        'url': 'url',
        'static_url': 'static_url'
    }

    def __init__(self, name=None, count=None, me=None, url=None, static_url=None):  # noqa: E501
        """AnnouncementReaction - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._count = None
        self._me = None
        self._url = None
        self._static_url = None
        self.discriminator = None
        self.name = name
        self.count = count
        self.me = me
        if url is not None:
            self.url = url
        if static_url is not None:
            self.static_url = static_url

    @property
    def name(self):
        """Gets the name of this AnnouncementReaction.  # noqa: E501

        The emoji used for the reaction. Either a unicode emoji, or a custom emoji's shortcode.  # noqa: E501

        :return: The name of this AnnouncementReaction.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AnnouncementReaction.

        The emoji used for the reaction. Either a unicode emoji, or a custom emoji's shortcode.  # noqa: E501

        :param name: The name of this AnnouncementReaction.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def count(self):
        """Gets the count of this AnnouncementReaction.  # noqa: E501

        The total number of users who have added this reaction.  # noqa: E501

        :return: The count of this AnnouncementReaction.  # noqa: E501
        :rtype: object
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this AnnouncementReaction.

        The total number of users who have added this reaction.  # noqa: E501

        :param count: The count of this AnnouncementReaction.  # noqa: E501
        :type: object
        """
        if count is None:
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def me(self):
        """Gets the me of this AnnouncementReaction.  # noqa: E501

        Whether the authorized user has added this reaction to the announcement.  # noqa: E501

        :return: The me of this AnnouncementReaction.  # noqa: E501
        :rtype: object
        """
        return self._me

    @me.setter
    def me(self, me):
        """Sets the me of this AnnouncementReaction.

        Whether the authorized user has added this reaction to the announcement.  # noqa: E501

        :param me: The me of this AnnouncementReaction.  # noqa: E501
        :type: object
        """
        if me is None:
            raise ValueError("Invalid value for `me`, must not be `None`")  # noqa: E501

        self._me = me

    @property
    def url(self):
        """Gets the url of this AnnouncementReaction.  # noqa: E501

        A link to the custom emoji.  # noqa: E501

        :return: The url of this AnnouncementReaction.  # noqa: E501
        :rtype: object
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this AnnouncementReaction.

        A link to the custom emoji.  # noqa: E501

        :param url: The url of this AnnouncementReaction.  # noqa: E501
        :type: object
        """

        self._url = url

    @property
    def static_url(self):
        """Gets the static_url of this AnnouncementReaction.  # noqa: E501

        A link to a non-animated version of the custom emoji.  # noqa: E501

        :return: The static_url of this AnnouncementReaction.  # noqa: E501
        :rtype: object
        """
        return self._static_url

    @static_url.setter
    def static_url(self, static_url):
        """Sets the static_url of this AnnouncementReaction.

        A link to a non-animated version of the custom emoji.  # noqa: E501

        :param static_url: The static_url of this AnnouncementReaction.  # noqa: E501
        :type: object
        """

        self._static_url = static_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnnouncementReaction, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnnouncementReaction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
