# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Application(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'website': 'object',
        'vapid_key': 'object'
    }

    attribute_map = {
        'name': 'name',
        'website': 'website',
        'vapid_key': 'vapid_key'
    }

    def __init__(self, name=None, website=None, vapid_key=None):  # noqa: E501
        """Application - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._website = None
        self._vapid_key = None
        self.discriminator = None
        self.name = name
        if website is not None:
            self.website = website
        if vapid_key is not None:
            self.vapid_key = vapid_key

    @property
    def name(self):
        """Gets the name of this Application.  # noqa: E501

        The name of your application.  # noqa: E501

        :return: The name of this Application.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Application.

        The name of your application.  # noqa: E501

        :param name: The name of this Application.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def website(self):
        """Gets the website of this Application.  # noqa: E501

        The website associated with your application.  # noqa: E501

        :return: The website of this Application.  # noqa: E501
        :rtype: object
        """
        return self._website

    @website.setter
    def website(self, website):
        """Sets the website of this Application.

        The website associated with your application.  # noqa: E501

        :param website: The website of this Application.  # noqa: E501
        :type: object
        """

        self._website = website

    @property
    def vapid_key(self):
        """Gets the vapid_key of this Application.  # noqa: E501

         Used for Push Streaming API. Returned with POST /api/v1/apps. Equivalent to PushSubscription#server_key.  # noqa: E501

        :return: The vapid_key of this Application.  # noqa: E501
        :rtype: object
        """
        return self._vapid_key

    @vapid_key.setter
    def vapid_key(self, vapid_key):
        """Sets the vapid_key of this Application.

         Used for Push Streaming API. Returned with POST /api/v1/apps. Equivalent to PushSubscription#server_key.  # noqa: E501

        :param vapid_key: The vapid_key of this Application.  # noqa: E501
        :type: object
        """

        self._vapid_key = vapid_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Application, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Application):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
