# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Field(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'value': 'object',
        'verified_at': 'object'
    }

    attribute_map = {
        'name': 'name',
        'value': 'value',
        'verified_at': 'verified_at'
    }

    def __init__(self, name=None, value=None, verified_at=None):  # noqa: E501
        """Field - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._value = None
        self._verified_at = None
        self.discriminator = None
        self.name = name
        self.value = value
        if verified_at is not None:
            self.verified_at = verified_at

    @property
    def name(self):
        """Gets the name of this Field.  # noqa: E501

        The key of a given field's key-value pair.  # noqa: E501

        :return: The name of this Field.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Field.

        The key of a given field's key-value pair.  # noqa: E501

        :param name: The name of this Field.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this Field.  # noqa: E501

        The value associated with the `name` key (HTML).  # noqa: E501

        :return: The value of this Field.  # noqa: E501
        :rtype: object
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Field.

        The value associated with the `name` key (HTML).  # noqa: E501

        :param value: The value of this Field.  # noqa: E501
        :type: object
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def verified_at(self):
        """Gets the verified_at of this Field.  # noqa: E501

        Timestamp of when the server verified a URL value for a rel=\"me\" link (ISO 8601 Datetime). Only defined if `value` is a verified URL. Otherwise, null.  # noqa: E501

        :return: The verified_at of this Field.  # noqa: E501
        :rtype: object
        """
        return self._verified_at

    @verified_at.setter
    def verified_at(self, verified_at):
        """Sets the verified_at of this Field.

        Timestamp of when the server verified a URL value for a rel=\"me\" link (ISO 8601 Datetime). Only defined if `value` is a verified URL. Otherwise, null.  # noqa: E501

        :param verified_at: The verified_at of this Field.  # noqa: E501
        :type: object
        """

        self._verified_at = verified_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Field, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Field):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
