# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IdFollowBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reblogs': 'object',
        'notify': 'object'
    }

    attribute_map = {
        'reblogs': 'reblogs',
        'notify': 'notify'
    }

    def __init__(self, reblogs=None, notify=None):  # noqa: E501
        """IdFollowBody - a model defined in Swagger"""  # noqa: E501
        self._reblogs = None
        self._notify = None
        self.discriminator = None
        if reblogs is not None:
            self.reblogs = reblogs
        if notify is not None:
            self.notify = notify

    @property
    def reblogs(self):
        """Gets the reblogs of this IdFollowBody.  # noqa: E501

        Receive this account's reblogs in home timeline?  # noqa: E501

        :return: The reblogs of this IdFollowBody.  # noqa: E501
        :rtype: object
        """
        return self._reblogs

    @reblogs.setter
    def reblogs(self, reblogs):
        """Sets the reblogs of this IdFollowBody.

        Receive this account's reblogs in home timeline?  # noqa: E501

        :param reblogs: The reblogs of this IdFollowBody.  # noqa: E501
        :type: object
        """

        self._reblogs = reblogs

    @property
    def notify(self):
        """Gets the notify of this IdFollowBody.  # noqa: E501

        Receive notifications when this account posts a status?  # noqa: E501

        :return: The notify of this IdFollowBody.  # noqa: E501
        :rtype: object
        """
        return self._notify

    @notify.setter
    def notify(self, notify):
        """Sets the notify of this IdFollowBody.

        Receive notifications when this account posts a status?  # noqa: E501

        :param notify: The notify of this IdFollowBody.  # noqa: E501
        :type: object
        """

        self._notify = notify

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IdFollowBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdFollowBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
