# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse4221(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'object',
        'details': 'InlineResponse4221Details'
    }

    attribute_map = {
        'error': 'error',
        'details': 'details'
    }

    def __init__(self, error=None, details=None):  # noqa: E501
        """InlineResponse4221 - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._details = None
        self.discriminator = None
        self.error = error
        self.details = details

    @property
    def error(self):
        """Gets the error of this InlineResponse4221.  # noqa: E501


        :return: The error of this InlineResponse4221.  # noqa: E501
        :rtype: object
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this InlineResponse4221.


        :param error: The error of this InlineResponse4221.  # noqa: E501
        :type: object
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def details(self):
        """Gets the details of this InlineResponse4221.  # noqa: E501


        :return: The details of this InlineResponse4221.  # noqa: E501
        :rtype: InlineResponse4221Details
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this InlineResponse4221.


        :param details: The details of this InlineResponse4221.  # noqa: E501
        :type: InlineResponse4221Details
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")  # noqa: E501

        self._details = details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse4221, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse4221):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
