# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class List(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'title': 'object',
        'replies_policy': 'object'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'replies_policy': 'replies_policy'
    }

    def __init__(self, id=None, title=None, replies_policy=None):  # noqa: E501
        """List - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._title = None
        self._replies_policy = None
        self.discriminator = None
        self.id = id
        self.title = title
        if replies_policy is not None:
            self.replies_policy = replies_policy

    @property
    def id(self):
        """Gets the id of this List.  # noqa: E501

        The internal database ID of the list. Cast from an integer, but not guaranteed to be a number.  # noqa: E501

        :return: The id of this List.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this List.

        The internal database ID of the list. Cast from an integer, but not guaranteed to be a number.  # noqa: E501

        :param id: The id of this List.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self):
        """Gets the title of this List.  # noqa: E501

        The user-defined title of the list.  # noqa: E501

        :return: The title of this List.  # noqa: E501
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this List.

        The user-defined title of the list.  # noqa: E501

        :param title: The title of this List.  # noqa: E501
        :type: object
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def replies_policy(self):
        """Gets the replies_policy of this List.  # noqa: E501

        The user-defined title of the list.  - `followed` = Show replies to any followed user. - `list` = Show replies to members of the list. - `none` = Show replies to no one.  # noqa: E501

        :return: The replies_policy of this List.  # noqa: E501
        :rtype: object
        """
        return self._replies_policy

    @replies_policy.setter
    def replies_policy(self, replies_policy):
        """Sets the replies_policy of this List.

        The user-defined title of the list.  - `followed` = Show replies to any followed user. - `list` = Show replies to members of the list. - `none` = Show replies to no one.  # noqa: E501

        :param replies_policy: The replies_policy of this List.  # noqa: E501
        :type: object
        """

        self._replies_policy = replies_policy

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(List, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, List):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
