# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Marker(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'home': 'MarkerHome',
        'notifications': 'MarkerNotifications'
    }

    attribute_map = {
        'home': 'home',
        'notifications': 'notifications'
    }

    def __init__(self, home=None, notifications=None):  # noqa: E501
        """Marker - a model defined in Swagger"""  # noqa: E501
        self._home = None
        self._notifications = None
        self.discriminator = None
        self.home = home
        self.notifications = notifications

    @property
    def home(self):
        """Gets the home of this Marker.  # noqa: E501


        :return: The home of this Marker.  # noqa: E501
        :rtype: MarkerHome
        """
        return self._home

    @home.setter
    def home(self, home):
        """Sets the home of this Marker.


        :param home: The home of this Marker.  # noqa: E501
        :type: MarkerHome
        """
        if home is None:
            raise ValueError("Invalid value for `home`, must not be `None`")  # noqa: E501

        self._home = home

    @property
    def notifications(self):
        """Gets the notifications of this Marker.  # noqa: E501


        :return: The notifications of this Marker.  # noqa: E501
        :rtype: MarkerNotifications
        """
        return self._notifications

    @notifications.setter
    def notifications(self, notifications):
        """Sets the notifications of this Marker.


        :param notifications: The notifications of this Marker.  # noqa: E501
        :type: MarkerNotifications
        """
        if notifications is None:
            raise ValueError("Invalid value for `notifications`, must not be `None`")  # noqa: E501

        self._notifications = notifications

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Marker, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Marker):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
