# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MarkerHome(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'last_read_id': 'object',
        'updated_at': 'object',
        'version': 'object'
    }

    attribute_map = {
        'last_read_id': 'last_read_id',
        'updated_at': 'updated_at',
        'version': 'version'
    }

    def __init__(self, last_read_id=None, updated_at=None, version=None):  # noqa: E501
        """MarkerHome - a model defined in Swagger"""  # noqa: E501
        self._last_read_id = None
        self._updated_at = None
        self._version = None
        self.discriminator = None
        self.last_read_id = last_read_id
        self.updated_at = updated_at
        self.version = version

    @property
    def last_read_id(self):
        """Gets the last_read_id of this MarkerHome.  # noqa: E501

        The ID of the most recently viewed entity.  # noqa: E501

        :return: The last_read_id of this MarkerHome.  # noqa: E501
        :rtype: object
        """
        return self._last_read_id

    @last_read_id.setter
    def last_read_id(self, last_read_id):
        """Sets the last_read_id of this MarkerHome.

        The ID of the most recently viewed entity.  # noqa: E501

        :param last_read_id: The last_read_id of this MarkerHome.  # noqa: E501
        :type: object
        """
        if last_read_id is None:
            raise ValueError("Invalid value for `last_read_id`, must not be `None`")  # noqa: E501

        self._last_read_id = last_read_id

    @property
    def updated_at(self):
        """Gets the updated_at of this MarkerHome.  # noqa: E501

        The timestamp of when the marker was set.  # noqa: E501

        :return: The updated_at of this MarkerHome.  # noqa: E501
        :rtype: object
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this MarkerHome.

        The timestamp of when the marker was set.  # noqa: E501

        :param updated_at: The updated_at of this MarkerHome.  # noqa: E501
        :type: object
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def version(self):
        """Gets the version of this MarkerHome.  # noqa: E501

        Used for locking to prevent write conflicts.  # noqa: E501

        :return: The version of this MarkerHome.  # noqa: E501
        :rtype: object
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this MarkerHome.

        Used for locking to prevent write conflicts.  # noqa: E501

        :param version: The version of this MarkerHome.  # noqa: E501
        :type: object
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarkerHome, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarkerHome):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
