# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Notification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'type': 'object',
        'created_at': 'object',
        'account': 'Account',
        'status': 'Status'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'created_at': 'created_at',
        'account': 'account',
        'status': 'status'
    }

    def __init__(self, id=None, type=None, created_at=None, account=None, status=None):  # noqa: E501
        """Notification - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._created_at = None
        self._account = None
        self._status = None
        self.discriminator = None
        self.id = id
        self.type = type
        self.created_at = created_at
        self.account = account
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this Notification.  # noqa: E501

        The id of the notification in the database.  # noqa: E501

        :return: The id of this Notification.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Notification.

        The id of the notification in the database.  # noqa: E501

        :param id: The id of this Notification.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def type(self):
        """Gets the type of this Notification.  # noqa: E501

        The type of event that resulted in the notification.  - `follow` = Someone followed you. - `follow_request` = Someone requested to follow you - `mention` = Someone mentioned you in their status. - `reblog` = Someone boosted one of your statuses - `favourite` = Someone favourited one of your statuses - `poll` = A poll you have voted in or created has ended. - `status` = Someone you enabled notifications for has posted a status.  # noqa: E501

        :return: The type of this Notification.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Notification.

        The type of event that resulted in the notification.  - `follow` = Someone followed you. - `follow_request` = Someone requested to follow you - `mention` = Someone mentioned you in their status. - `reblog` = Someone boosted one of your statuses - `favourite` = Someone favourited one of your statuses - `poll` = A poll you have voted in or created has ended. - `status` = Someone you enabled notifications for has posted a status.  # noqa: E501

        :param type: The type of this Notification.  # noqa: E501
        :type: object
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def created_at(self):
        """Gets the created_at of this Notification.  # noqa: E501

        The timestamp of the notification.  # noqa: E501

        :return: The created_at of this Notification.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this Notification.

        The timestamp of the notification.  # noqa: E501

        :param created_at: The created_at of this Notification.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def account(self):
        """Gets the account of this Notification.  # noqa: E501


        :return: The account of this Notification.  # noqa: E501
        :rtype: Account
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this Notification.


        :param account: The account of this Notification.  # noqa: E501
        :type: Account
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")  # noqa: E501

        self._account = account

    @property
    def status(self):
        """Gets the status of this Notification.  # noqa: E501


        :return: The status of this Notification.  # noqa: E501
        :rtype: Status
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Notification.


        :param status: The status of this Notification.  # noqa: E501
        :type: Status
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Notification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Notification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
