# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Tag(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'url': 'object',
        'history': 'object'
    }

    attribute_map = {
        'name': 'name',
        'url': 'url',
        'history': 'history'
    }

    def __init__(self, name=None, url=None, history=None):  # noqa: E501
        """Tag - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._url = None
        self._history = None
        self.discriminator = None
        self.name = name
        self.url = url
        if history is not None:
            self.history = history

    @property
    def name(self):
        """Gets the name of this Tag.  # noqa: E501

        The value of the hashtag after the # sign.  # noqa: E501

        :return: The name of this Tag.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Tag.

        The value of the hashtag after the # sign.  # noqa: E501

        :param name: The name of this Tag.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def url(self):
        """Gets the url of this Tag.  # noqa: E501

        A link to the hashtag on the instance.  # noqa: E501

        :return: The url of this Tag.  # noqa: E501
        :rtype: object
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Tag.

        A link to the hashtag on the instance.  # noqa: E501

        :param url: The url of this Tag.  # noqa: E501
        :type: object
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def history(self):
        """Gets the history of this Tag.  # noqa: E501

        Usage statistics for given days.  # noqa: E501

        :return: The history of this Tag.  # noqa: E501
        :rtype: object
        """
        return self._history

    @history.setter
    def history(self, history):
        """Sets the history of this Tag.

        Usage statistics for given days.  # noqa: E501

        :param history: The history of this Tag.  # noqa: E501
        :type: object
        """

        self._history = history

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Tag, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Tag):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
