# coding: utf-8

"""
    Mastodon API

    The API for interacting with Mastodon.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class V1AccountsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'object',
        'email': 'object',
        'password': 'object',
        'agreement': 'object',
        'locale': 'object',
        'reason': 'object'
    }

    attribute_map = {
        'username': 'username',
        'email': 'email',
        'password': 'password',
        'agreement': 'agreement',
        'locale': 'locale',
        'reason': 'reason'
    }

    def __init__(self, username=None, email=None, password=None, agreement=None, locale=None, reason=None):  # noqa: E501
        """V1AccountsBody - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._email = None
        self._password = None
        self._agreement = None
        self._locale = None
        self._reason = None
        self.discriminator = None
        self.username = username
        self.email = email
        self.password = password
        self.agreement = agreement
        if locale is not None:
            self.locale = locale
        if reason is not None:
            self.reason = reason

    @property
    def username(self):
        """Gets the username of this V1AccountsBody.  # noqa: E501

        The desired username for the account.  # noqa: E501

        :return: The username of this V1AccountsBody.  # noqa: E501
        :rtype: object
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this V1AccountsBody.

        The desired username for the account.  # noqa: E501

        :param username: The username of this V1AccountsBody.  # noqa: E501
        :type: object
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def email(self):
        """Gets the email of this V1AccountsBody.  # noqa: E501

        The email address to be used for login.  # noqa: E501

        :return: The email of this V1AccountsBody.  # noqa: E501
        :rtype: object
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this V1AccountsBody.

        The email address to be used for login.  # noqa: E501

        :param email: The email of this V1AccountsBody.  # noqa: E501
        :type: object
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self):
        """Gets the password of this V1AccountsBody.  # noqa: E501

        The password to be used for login.  # noqa: E501

        :return: The password of this V1AccountsBody.  # noqa: E501
        :rtype: object
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this V1AccountsBody.

        The password to be used for login.  # noqa: E501

        :param password: The password of this V1AccountsBody.  # noqa: E501
        :type: object
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def agreement(self):
        """Gets the agreement of this V1AccountsBody.  # noqa: E501

        Whether the user agrees to the local rules, terms, and policies. **These should be presented to the user in order to allow them to consent before setting this parameter to `true`**.  # noqa: E501

        :return: The agreement of this V1AccountsBody.  # noqa: E501
        :rtype: object
        """
        return self._agreement

    @agreement.setter
    def agreement(self, agreement):
        """Sets the agreement of this V1AccountsBody.

        Whether the user agrees to the local rules, terms, and policies. **These should be presented to the user in order to allow them to consent before setting this parameter to `true`**.  # noqa: E501

        :param agreement: The agreement of this V1AccountsBody.  # noqa: E501
        :type: object
        """
        if agreement is None:
            raise ValueError("Invalid value for `agreement`, must not be `None`")  # noqa: E501

        self._agreement = agreement

    @property
    def locale(self):
        """Gets the locale of this V1AccountsBody.  # noqa: E501

        The language of the confirmation email that will be sent.  # noqa: E501

        :return: The locale of this V1AccountsBody.  # noqa: E501
        :rtype: object
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this V1AccountsBody.

        The language of the confirmation email that will be sent.  # noqa: E501

        :param locale: The locale of this V1AccountsBody.  # noqa: E501
        :type: object
        """

        self._locale = locale

    @property
    def reason(self):
        """Gets the reason of this V1AccountsBody.  # noqa: E501

        Text that will be reviewed by moderators if registrations require manual approval.  # noqa: E501

        :return: The reason of this V1AccountsBody.  # noqa: E501
        :rtype: object
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this V1AccountsBody.

        Text that will be reviewed by moderators if registrations require manual approval.  # noqa: E501

        :param reason: The reason of this V1AccountsBody.  # noqa: E501
        :type: object
        """

        self._reason = reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1AccountsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AccountsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
